[tweaks.fixes]
# Keeps rendering world as is when changing interior via ENEX marker.
dont-cull-world-on-enex = true

# Reduces radius of the CCarGenerator::CheckForBlockage by 20 times, allowing Hunter to spawn next to the Leviathan.
fix-car-generator-blockage = true

# Allows police bikes to utilize CCarAI::MakeWayForCarWithSiren too.
fix-police-bike-siren = true

# Fixes uncrouching due to PS2 button collisions when using first person weapons such as a sniper rifle.
fix-zoom-uncrouching = true

# Makes the number of garage slots in Ganton consistent with other garages.
ganton-garage-four-slots = true

# When CJ dies from fire, his body will char like other pedestrians'.
scorched-cj = true

[tweaks.gameplay]
# Allows climbing in interiors.
climb-everywhere = true

# Removes artificial slowdown of player's vehicle in special cull zones.
disable-extra-air-resistance = true

# Allows ducking with any weapon, regardless of its type.
duck-with-any-weapon = true

# Allows jumping with weapons marked as heavy in the weapon.dat, such as a minigun.
jump-with-heavy-weapons = true

# Allows sprinting on any surface during any mission,
# during the animation of putting on/taking off goggles,
# and while standing on entities (trains).
sprint-everywhere = true

# Recruited gang members will follow the player into every interior.
always-warp-gang-with-player = true

# Allows climbing on vehicles other than boats and trains.
# Climbing task is no longer aborted on moving trains.
#
# ignore-col-spheres: Collision spheres may prevent climbing on some vehicles at certain angles.
# 'allow-vaulting': Allows CJ to vault on some vehicle parts that are thin enough, but it may not look right.
climbable-vehicles = { enabled = true, ignore-col-spheres = true, allow-vaulting = true }

[tweaks.hud]
# Displays ammo even if player has more than 9998.
# Also displays the actual amount for the flamethrower (the game divides by 10 for some reason).
always-show-ammo = true

[tweaks.visuals]
# Disables heat haze effect.
disable-heat-haze = true

# Disables speed blur effect.
disable-speed-blur = true
